services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - mongo
    command:  uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  celery_worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    depends_on:
      - redis
      - mongo
    command: celery -A worker.celery_app worker --loglevel=info
    


  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
